// meetings.js
const meetings = [
  {
    title: "Pre-sessional workshop on the Work Programme",
    link: "https://unfccc.int/event/pre-sessional-workshop",
    date: "05 Nov 2022",
    time: "08:30 - 18:00",
    room: "Meeting Room 2",
    access: "Limited access",
  },
  {
    title: "4th workshop under the Glasgow–Sharm el-Sheikh work programme",
    link: "https://unfccc.int/event/4th-workshop",
    date: "05 Nov 2022",
    time: "09:00 - 18:00",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    "title": "Example Meeting",
    "link": "https://example.com",
    "date": "2024-08-23",
    "time": "10:00 - 11:00",
    "room": "Meeting Room 2",
    "access": "Open meeting"
  },
  {
    "title": "Example Meeting",
    "link": "https://asdasd.com",
    "date": "2024-08-23",
    "time": "10:00 - 11:00",
    "room": "Meeting Room 2",
    "access": "Open meeting"
  },
  {
    "title": "Example Meeting",
    "link": "https:asdasdxample.com",
    "date": "2024-08-24",
    "time": "10:00 - 11:00",
    "room": "Meeting Room 2",
    "access": "Open meeting"
  },
  {
    "title": "Example Meeting",
    "link": "https://asdasd.com",
    "date": "2024-08-24",
    "time": "10:00 - 11:00",
    "room": "Meeting Room 2",
    "access": "Open meeting"
  },
  {
    "title": "Upcoming Meeting",
    "link": "https://example.com",
    "date": "2024-08-25",
    "time": "14:00 - 15:00",
    "room": "Meeting Room 5",
    "access": "Limited access"
  },
    {
    title:
      "Pre-sessional workshop on the Work Programme for urgently scaling up Mitigation ambition and implementation referred to in paragraph 27 of decision 1/CMA.3 (MWP)",
    link: "https://unfccc.int/event/pre-sessional-workshop-on-the-work-programme-for-urgently-scaling-up-mitigation-ambition-and-0",
    date: "05 Nov 2022",
    time: "08:30 - 18:00",
    room: "Meeting Room 2",
    access: "Limited access",
  },
  {
    title:
      "4th workshop under the Glasgow–Sharm el-Sheikh work programme on the Global Goal on Adaptation on Communicating and reporting on adaptation priorities (GGA WS)",
    link: "https://unfccc.int/event/4th-workshop-under-the-glasgow-sharm-el-sheikh-work-programme-on-the-global-goal-on-adaptation-on",
    date: "05 Nov 2022",
    time: "09:00 - 18:00",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    title: "Art. 6.4 SB - Observer's Room 1",
    link: "https://unfccc.int/event/art-64-sb-observer-s-room-1",
    date: "05 Nov 2022",
    time: "09:00 - 23:59",
    room: "Meeting Room 7",
    access: "Limited access",
  },
  {
    title: "Art. 6.4 SB - Observers' Room 2",
    link: "https://unfccc.int/event/art-64-sb-observers-room-2",
    date: "05 Nov 2022",
    time: "09:00 - 23:59",
    room: "Meeting Room 11",
    access: "Limited access",
  },
  {
    title: "Expert-input Roundtable - Group 2",
    link: "https://unfccc.int/event/expert-input-roundtable-group-2-0",
    date: "05 Nov 2022",
    time: "09:00 - 13:00",
    room: "Meeting Room 6",
    access: "Open meeting",
  },
  {
    title: "Expert-input Roundtable - Group 3",
    link: "https://unfccc.int/event/expert-input-roundtable-group-3",
    date: "05 Nov 2022",
    time: "09:00 - 13:00",
    room: "Meeting Room 3",
    access: "Open meeting",
  },
  {
    title:
      "Fourth Technical Expert Dialogue on the New Collective Quantified Goal on Climate Finance (TED4)",
    link: "https://unfccc.int/event/fourth-technical-expert-dialogue-on-the-new-collective-quantified-goal-on-climate-finance-ted4",
    date: "05 Nov 2022",
    time: "09:00 - 19:00",
    room: "Plenary - Ramses",
    access: "Open meeting",
  },
  {
    title: "GGA WS - Breakout room 1",
    link: "https://unfccc.int/event/gga-ws-breakout-room-1",
    date: "05 Nov 2022",
    time: "09:00 - 12:00",
    room: "Meeting Room 17",
    access: "Open meeting",
  },
  {
    title: "Expert-Input Roundtable - Group 2",
    link: "https://unfccc.int/event/expert-input-roundtable-group-2",
    date: "05 Nov 2022",
    time: "14:00 - 18:00",
    room: "Meeting Room 6",
    access: "Open meeting",
  },
  {
    title: "Expert-input Roundtable - Group 3",
    link: "https://unfccc.int/event/expert-input-roundtable-group-3-0",
    date: "05 Nov 2022",
    time: "14:00 - 18:00",
    room: "Meeting Room 3",
    access: "Open meeting",
  },
  {
    title:
      "Greenriver: Messages to world leaders from the Global Youth Climate Week",
    link: "https://unfccc.int/event/greenriver-messages-to-world-leaders-from-the-global-youth-climate-week",
    date: "06 Nov 2022",
    time: "10:30 - 11:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "AIPP - Indigenous Peoples' Assessemet: Our contributions to the National Climate Plans and Policies",
    link: "https://unfccc.int/event/aipp-indigenous-peoples-assessemet-our-contributions-to-the-national-climate-plans-and-policies",
    date: "06 Nov 2022",
    time: "11:00 - 11:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Actions Vitales pour le Développement Durable (AVD)",
    link: "https://unfccc.int/event/actions-vitales-pour-le-developpement-durable-avd",
    date: "06 Nov 2022",
    time: "11:30 - 12:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "Ceremonial opening of COP 27 followed by opening of COP, followed by opening of CMP, followed by opening of CMA",
    link: "https://unfccc.int/event/ceremonial-opening-of-cop-27-followed-by-opening-of-cop-followed-by-opening-of-cmp-followed-by",
    date: "06 Nov 2022",
    time: "11:30 - 14:00",
    room: "Plenary - Ramses",
    access: "Open meeting",
  },
  {
    title: "Ceremonial opening of COP 27 Overflow",
    link: "https://unfccc.int/event/ceremonial-opening-of-cop-27-overflow",
    date: "06 Nov 2022",
    time: "11:30 - 14:00",
    room: "Meeting Room 2",
    access: "Open meeting",
  },
  {
    title: "Ceremonial opening of COP 27 Overflow",
    link: "https://unfccc.int/event/ceremonial-opening-of-cop-27-overflow-0",
    date: "06 Nov 2022",
    time: "11:30 - 14:00",
    room: "Meeting Room 1",
    access: "Open meeting",
  },
  {
    title:
      "ICLEI announcing Multilevel Action Pavilion and LGMA inputs to COP27 through #MultilevelActionDelivers",
    link: "https://unfccc.int/event/iclei-announcing-multilevel-action-pavilion-and-lgma-inputs-to-cop27-through",
    date: "06 Nov 2022",
    time: "12:00 - 12:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "CANGO",
    link: "https://unfccc.int/event/cango",
    date: "06 Nov 2022",
    time: "13:00 - 13:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "COP Presidency and UN Climate Change Executive Secretary",
    link: "https://unfccc.int/event/cop-presidency-and-un-climate-change-executive-secretary",
    date: "06 Nov 2022",
    time: "13:30 - 14:00",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title: "Global Campaign to Demand Climate Justice",
    link: "https://unfccc.int/event/global-campaign-to-demand-climate-justice",
    date: "06 Nov 2022",
    time: "14:00 - 14:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "WMO: Provisional State of the Climate in 2022 report",
    link: "https://unfccc.int/event/wmo-provisional-state-of-the-climate-in-2022-report",
    date: "06 Nov 2022",
    time: "14:00 - 14:30",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title: "The Save Movement",
    link: "https://unfccc.int/event/the-save-movement",
    date: "06 Nov 2022",
    time: "14:30 - 15:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Abibimman Foundation",
    link: "https://unfccc.int/event/abibimman-foundation-18",
    date: "06 Nov 2022",
    time: "15:00 - 15:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "G77 & China - Loss & Damage",
    link: "https://unfccc.int/event/g77-china-loss-damage",
    date: "06 Nov 2022",
    time: "15:00 - 17:00",
    room: "Meeting Room 13",
    access: "Limited access",
  },
  {
    title: "GST/TD Co facilitator Bilateral",
    link: "https://unfccc.int/event/gst/td-co-facilitator-bilateral",
    date: "06 Nov 2022",
    time: "15:00 - 17:00",
    room: "Meeting Room 9",
    access: "Open meeting",
  },
  {
    title:
      "SBSTA opening, followed by SBI opening, followed by Joint Plenary meeting of COP, CMP, CMA, SBSTA and SBI to take up statements",
    link: "https://unfccc.int/event/sbsta-opening-followed-by-sbi-opening-followed-by-joint-plenary-meeting-of-cop-cmp-cma-sbsta-and-sbi",
    date: "06 Nov 2022",
    time: "15:00 - 23:30",
    room: "Plenary - Ramses",
    access: "Open meeting",
  },
  {
    title:
      "Friends of the Earth International: Expectations and demands for climate justice",
    link: "https://unfccc.int/event/friends-of-the-earth-international-expectations-and-demands-for-climate-justice",
    date: "06 Nov 2022",
    time: "16:00 - 16:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "Guidance on cooperative approaches referred to in Article 6, paragraph 2, of the Paris Agreement and in decision 2/CMA.3",
    link: "https://unfccc.int/event/guidance-on-cooperative-approaches-referred-to-in-article-6-paragraph-2-of-the-paris-agreement-and-3",
    date: "06 Nov 2022",
    time: "16:00 - 18:00",
    room: "Meeting Room 2",
    access: "Open meeting",
  },
  {
    title:
      "Technical session for implementing the work plan activities of the forum on the impacts of the implementation of response measures",
    link: "https://unfccc.int/event/technical-session-for-implementing-the-work-plan-activities-of-the-forum-on-the-impacts-of-the",
    date: "06 Nov 2022",
    time: "16:30 - 18:30",
    room: "Meeting Room 6",
    access: "Open meeting",
  },
  {
    title:
      "Unitarian Universalist Service Committee: Methane Removal:  On the Critical Path to Avoiding 0.6 degrees of Warming by 2050",
    link: "https://unfccc.int/event/unitarian-universalist-service-committee-methane-removal-on-the-critical-path-to-avoiding-06-degrees",
    date: "06 Nov 2022",
    time: "16:30 - 17:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Fourth review of the Adaptation Fund",
    link: "https://unfccc.int/event/fourth-review-of-the-adaptation-fund",
    date: "06 Nov 2022",
    time: "17:00 - 17:30",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    title: "Koronivia Joint on Agriculture",
    link: "https://unfccc.int/event/koronivia-joint-on-agriculture-1",
    date: "06 Nov 2022",
    time: "17:00 - 18:00",
    room: "Meeting Room 17",
    access: "Open meeting",
  },
  {
    title:
      "Matters relating to the work programme for urgently scaling up mitigation ambition and implementation referred to in paragraph 27 of decision 1/CMA.3",
    link: "https://unfccc.int/event/matters-relating-to-the-work-programme-for-urgently-scaling-up-mitigation-ambition-and-1",
    date: "06 Nov 2022",
    time: "17:00 - 18:00",
    room: "Meeting Room 1",
    access: "Open meeting",
  },
  {
    title: "Report of the WIM ExCom",
    link: "https://unfccc.int/event/report-of-the-wim-excom",
    date: "06 Nov 2022",
    time: "17:00 - 19:00",
    room: "Meeting Room 5",
    access: "Open meeting",
  },
  {
    title: "Report of the Adaptation Fund Board",
    link: "https://unfccc.int/event/report-of-the-adaptation-fund-board",
    date: "06 Nov 2022",
    time: "17:30 - 17:45",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    title: "Matters relating to Adaptation Fund",
    link: "https://unfccc.int/event/matters-relating-to-adaptation-fund",
    date: "06 Nov 2022",
    time: "17:45 - 18:00",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    title: "SIDs Daily Coordination Evening Meeting",
    link: "https://unfccc.int/event/sids-daily-coordination-evening-meeting-9",
    date: "06 Nov 2022",
    time: "18:00 - 19:00",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    title: "Bilateral with Co-Facilitators PR",
    link: "https://unfccc.int/event/bilateral-with-co-facilitators-pr",
    date: "07 Nov 2022",
    time: "09:00 - 12:00",
    room: "Meeting Room 8",
    access: "Open meeting",
  },
  {
    title: "Business Council for Sustainable Energy",
    link: "https://unfccc.int/event/business-council-for-sustainable-energy",
    date: "07 Nov 2022",
    time: "09:00 - 09:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "AIPP: Indigenous Peoples' Assessment: Our contributions to the National Climate Plans and Policies",
    link: "https://unfccc.int/event/aipp-indigenous-peoples-assessment-our-contributions-to-the-national-climate-plans-and-policies",
    date: "07 Nov 2022",
    time: "09:30 - 10:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Session 1:  UGIH Core-Partner Introductory Remarks",
    link: "https://unfccc.int/event/session-1-ugih-core-partner-introductory-remarks",
    date: "07 Nov 2022",
    time: "10:00 - 11:00",
    room: "Innovation-Hub Pavilion",
    access: "Open meeting",
  },
  {
    title: "WEDO: African Women & Girls Demand Climate Justice",
    link: "https://unfccc.int/event/wedo-african-women-girls-demand-climate-justice",
    date: "07 Nov 2022",
    time: "10:00 - 10:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "World Trade Organization: WTO and Climate Change",
    link: "https://unfccc.int/event/world-trade-organization-wto-and-climate-change",
    date: "07 Nov 2022",
    time: "10:30 - 11:00",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title: "Youth Climate Report 2022",
    link: "https://unfccc.int/event/youth-climate-report-2022",
    date: "07 Nov 2022",
    time: "10:30 - 11:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Center for Biological Diversity",
    link: "https://unfccc.int/event/center-for-biological-diversity-3",
    date: "07 Nov 2022",
    time: "11:00 - 11:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "Session 2: High-level session on systems change and climate and sustainability innovations (Part 1)",
    link: "https://unfccc.int/event/session-2-high-level-session-on-systems-change-and-climate-and-sustainability-innovations-part-1",
    date: "07 Nov 2022",
    time: "11:00 - 12:00",
    room: "Innovation-Hub Pavilion",
    access: "Open meeting",
  },
  {
    title: "CAN: Climate Action Network Press Briefing on COP27",
    link: "https://unfccc.int/event/can-climate-action-network-press-briefing-on-cop27",
    date: "07 Nov 2022",
    time: "11:30 - 12:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Council on Energy, Environment and Water",
    link: "https://unfccc.int/event/council-on-energy-environment-and-water-2",
    date: "07 Nov 2022",
    time: "12:00 - 12:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "Session 3: High-level session on systems change and climate and sustainability innovations (part 2)",
    link: "https://unfccc.int/event/session-3-high-level-session-on-systems-change-and-climate-and-sustainability-innovations-part-2",
    date: "07 Nov 2022",
    time: "12:00 - 13:00",
    room: "Innovation-Hub Pavilion",
    access: "Open meeting",
  },
  {
    title:
      "Opening Ceremony with interventions from President of the Republic, UN SG, King of the United Kingdom, Leader of UAE",
    link: "https://unfccc.int/event/opening-ceremony-with-interventions-from-president-of-the-republic-un-sg-king-of-the-united-kingdom",
    date: "07 Nov 2022",
    time: "12:15 - 13:30",
    room: "Plenary - Nefertiti",
    access: "Open meeting",
  },
  {
    title:
      "Overflow for plenary Nefertiti - Opening Ceremony with interventions from President of the Republic, UN SG, King of the United Kingdom, Leader of UAE",
    link: "https://unfccc.int/event/overflow-for-plenary-nefertiti-opening-ceremony-with-interventions-from-president-of-the-republic-un",
    date: "07 Nov 2022",
    time: "12:15 - 13:30",
    room: "Plenary - Ramses",
    access: "Open meeting",
  },
  {
    title: "Buddhist Tzu Chi Foundation",
    link: "https://unfccc.int/event/buddhist-tzu-chi-foundation-17",
    date: "07 Nov 2022",
    time: "12:30 - 13:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Global Green Environmental Network",
    link: "https://unfccc.int/event/global-green-environmental-network",
    date: "07 Nov 2022",
    time: "13:00 - 13:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "GST/Technical Dialogue Creative Space",
    link: "https://unfccc.int/event/gst/technical-dialogue-creative-space",
    date: "07 Nov 2022",
    time: "13:00 - 14:00",
    room: "Meeting Room 5",
    access: "Open meeting",
  },
  {
    title:
      "Guidance on cooperative approaches referred to in Article 6, paragraph 2, of the Paris Agreement and in decision 2/CMA.3",
    link: "https://unfccc.int/event/guidance-on-cooperative-approaches-referred-to-in-article-6-paragraph-2-of-the-paris-agreement-and-4",
    date: "07 Nov 2022",
    time: "13:00 - 14:00",
    room: "Meeting Room 6",
    access: "Open meeting",
  },
  {
    title:
      "IC - Emissions from fuel used for international aviation and maritime transport",
    link: "https://unfccc.int/event/ic-emissions-from-fuel-used-for-international-aviation-and-maritime-transport",
    date: "07 Nov 2022",
    time: "13:00 - 14:00",
    room: "Meeting Room 3",
    access: "Open meeting",
  },
  {
    title: "Informal Consultations on Gender and Climate Change",
    link: "https://unfccc.int/event/informal-consultations-on-gender-and-climate-change",
    date: "07 Nov 2022",
    time: "13:00 - 14:00",
    room: "Meeting Room 4",
    access: "Open meeting",
  },
  {
    title:
      "Overflow: Presentation of structure Expert Dialogue synthesis report to Parties",
    link: "https://unfccc.int/event/overflow-presentation-of-structure-expert-dialogue-synthesis-report-to-parties",
    date: "07 Nov 2022",
    time: "13:00 - 14:00",
    room: "Meeting Room 13",
    access: "Open meeting",
  },
  {
    title:
      "Presentation of Structure Expert Dialogue Synthesis Report to Parties",
    link: "https://unfccc.int/event/presentation-of-structure-expert-dialogue-synthesis-report-to-parties",
    date: "07 Nov 2022",
    time: "13:00 - 14:00",
    room: "Meeting Room 17",
    access: "Open meeting",
  },
  {
    title:
      "Session 4: Showcasing an expanded climate innovation platform: Focus on human needs and stakeholders as solution providers",
    link: "https://unfccc.int/event/session-4-showcasing-an-expanded-climate-innovation-platform-focus-on-human-needs-and-stakeholders",
    date: "07 Nov 2022",
    time: "13:00 - 14:00",
    room: "Innovation-Hub Pavilion",
    access: "Open meeting",
  },
  {
    title: "Seventh review of the Financial Mechanism",
    link: "https://unfccc.int/event/seventh-review-of-the-financial-mechanism",
    date: "07 Nov 2022",
    time: "13:00 - 14:00",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    title:
      "TAPP Coalition: Launch of COP27 Climate Agreement for Food and Farming",
    link: "https://unfccc.int/event/tapp-coalition-launch-of-cop27-climate-agreement-for-food-and-farming",
    date: "07 Nov 2022",
    time: "13:30 - 14:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "First periodic assessment referred to in paragraph 69 of decision 1/CP 21",
    link: "https://unfccc.int/event/first-periodic-assessment-referred-to-in-paragraph-69-of-decision-1/cp-21",
    date: "07 Nov 2022",
    time: "14:00 - 15:00",
    room: "Meeting Room 3",
    access: "Open meeting",
  },
  {
    title: "Matters relating to Action for Climate Empowerment",
    link: "https://unfccc.int/event/matters-relating-to-action-for-climate-empowerment-0",
    date: "07 Nov 2022",
    time: "14:00 - 15:00",
    room: "Meeting Room 4",
    access: "Open meeting",
  },
  {
    title: "Matters relating to the Adaptation Fund",
    link: "https://unfccc.int/event/matters-relating-to-the-adaptation-fund-7",
    date: "07 Nov 2022",
    time: "14:00 - 15:00",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    title:
      "Matters relating to the work programme for urgently scaling up mitigation ambition and implementation referred to in paragraph 27 of decision 1/CMA.3",
    link: "https://unfccc.int/event/matters-relating-to-the-work-programme-for-urgently-scaling-up-mitigation-ambition-and-3",
    date: "07 Nov 2022",
    time: "14:00 - 15:00",
    room: "Meeting Room 17",
    access: "Open meeting",
  },
  {
    title:
      "Reviews on a voluntary basis of information reported pursuant to decision 18/CMA.1, annex, chapter IV, and training courses needed",
    link: "https://unfccc.int/event/reviews-on-a-voluntary-basis-of-information-reported-pursuant-to-decision-18/cma1-annex-chapter-iv",
    date: "07 Nov 2022",
    time: "14:00 - 15:00",
    room: "Meeting Room 5",
    access: "Open meeting",
  },
  {
    title:
      "Work programme under the framework for NMAs referred to in Article 6.8, of the Paris Agreement and in decision 4/CMA.3",
    link: "https://unfccc.int/event/work-programme-under-the-framework-for-nmas-referred-to-in-article-68-of-the-paris-agreement-and-in",
    date: "07 Nov 2022",
    time: "14:00 - 15:00",
    room: "Meeting Room 2",
    access: "Open meeting",
  },
  {
    title:
      "Session 5: Innovation in the UNFCCC process: National systems of innovation and digitalization",
    link: "https://unfccc.int/event/session-5-innovation-in-the-unfccc-process-national-systems-of-innovation-and-digitalization",
    date: "07 Nov 2022",
    time: "14:00 - 16:00",
    room: "Innovation-Hub Pavilion",
    access: "Open meeting",
  },
  {
    title:
      "TERRE Policy Centre: Worldwide appeal to take measures on Flood and Drought",
    link: "https://unfccc.int/event/terre-policy-centre-worldwide-appeal-to-take-measures-on-flood-and-drought",
    date: "07 Nov 2022",
    time: "14:00 - 14:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Greenpeace",
    link: "https://unfccc.int/event/greenpeace-0",
    date: "07 Nov 2022",
    time: "14:30 - 15:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "GHG Inventory review training Conventions",
    link: "https://unfccc.int/event/ghg-inventory-review-training-conventions",
    date: "07 Nov 2022",
    time: "15:00 - 16:00",
    room: "Meeting Room 17",
    access: "Open meeting",
  },
  {
    title: "Joint annual report of the TEC and the CTCN",
    link: "https://unfccc.int/event/joint-annual-report-of-the-tec-and-the-ctcn",
    date: "07 Nov 2022",
    time: "15:00 - 16:00",
    room: "Meeting Room 3",
    access: "Open meeting",
  },
  {
    title: "Matters relating to the Standing Committee on Finance",
    link: "https://unfccc.int/event/matters-relating-to-the-standing-committee-on-finance-0",
    date: "07 Nov 2022",
    time: "15:00 - 16:00",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    title: "Santiago Network of the WIM",
    link: "https://unfccc.int/event/santiago-network-of-the-wim",
    date: "07 Nov 2022",
    time: "15:00 - 16:00",
    room: "Meeting Room 4",
    access: "Open meeting",
  },
  {
    title:
      "Second periodic review of the long-term global goal under the Convention and of overall progress towards achieving it",
    link: "https://unfccc.int/event/second-periodic-review-of-the-long-term-global-goal-under-the-convention-and-of-overall-progress",
    date: "07 Nov 2022",
    time: "15:00 - 16:00",
    room: "Meeting Room 5",
    access: "Open meeting",
  },
  {
    title: "Scientists Warning Europe",
    link: "https://unfccc.int/event/scientists-warning-europe",
    date: "07 Nov 2022",
    time: "15:00 - 15:30",
    room: "Press Conference Room - Luxor",
    access: "Limited access",
  },
  {
    title: "Pan African Climate Justice Alliance",
    link: "https://unfccc.int/event/pan-african-climate-justice-alliance-1",
    date: "07 Nov 2022",
    time: "15:30 - 16:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "BR NC review training Convention",
    link: "https://unfccc.int/event/br-nc-review-training-convention",
    date: "07 Nov 2022",
    time: "16:00 - 17:00",
    room: "Meeting Room 17",
    access: "Open meeting",
  },
  {
    title: "Launch of the Action Plan on Early Warning Systems",
    link: "https://unfccc.int/event/launch-of-the-action-plan-on-early-warning-systems-0",
    date: "07 Nov 2022",
    time: "16:00 - 17:00",
    room: "Meeting Room 25",
    access: "Open meeting",
  },
  {
    title:
      "Matters relating to the forum on the impact of the implementation of response measures serving the Convention, the Kyoto Protocol and the Paris Agreement",
    link: "https://unfccc.int/event/matters-relating-to-the-forum-on-the-impact-of-the-implementation-of-response-measures-serving-the",
    date: "07 Nov 2022",
    time: "16:00 - 17:00",
    room: "Meeting Room 5",
    access: "Open meeting",
  },
  {
    title:
      "Opening meeting of the second meeting of the Technical Dialogue under the first Global Stocktake (GST TD)",
    link: "https://unfccc.int/event/opening-meeting-of-the-second-meeting-of-the-technical-dialogue-under-the-first-global-stocktake-gst",
    date: "07 Nov 2022",
    time: "16:00 - 17:00",
    room: "Side Event Room 5 - Memphis",
    access: "Open meeting",
  },
  {
    title: "Overflow: Opening of the second meeting of the GST TD",
    link: "https://unfccc.int/event/overflow-opening-of-the-second-meeting-of-the-gst-td",
    date: "07 Nov 2022",
    time: "16:00 - 17:00",
    room: "Side Event Room 6 - Osiris",
    access: "Open meeting",
  },
  {
    title: "Poznan strategic programme on technology transfer",
    link: "https://unfccc.int/event/poznan-strategic-programme-on-technology-transfer-1",
    date: "07 Nov 2022",
    time: "16:00 - 17:00",
    room: "Meeting Room 3",
    access: "Open meeting",
  },
  {
    title: "Report of the Adaptation Committee",
    link: "https://unfccc.int/event/report-of-the-adaptation-committee",
    date: "07 Nov 2022",
    time: "16:00 - 17:00",
    room: "Meeting Room 4",
    access: "Open meeting",
  },
  {
    title:
      "Session 6: Global south - global north cooperation on the digital and green twin transition",
    link: "https://unfccc.int/event/session-6-global-south-global-north-cooperation-on-the-digital-and-green-twin-transition",
    date: "07 Nov 2022",
    time: "16:00 - 17:00",
    room: "Innovation-Hub Pavilion",
    access: "Open meeting",
  },
  {
    title: "EIT Climate-KIC",
    link: "https://unfccc.int/event/eit-climate-kic",
    date: "07 Nov 2022",
    time: "16:00 - 16:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Prime Minister of the Czech Republic",
    link: "https://unfccc.int/event/prime-minister-of-the-czech-republic",
    date: "07 Nov 2022",
    time: "16:00 - 16:30",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title: "First Part of the High-Level Segment",
    link: "https://unfccc.int/event/first-part-of-the-high-level-segment-0",
    date: "07 Nov 2022",
    time: "16:00 - 22:00",
    room: "Plenary - Nefertiti",
    access: "Open meeting",
  },
  {
    title:
      "Guidance to the Green Climate Fund and Guidance to the Global Environment Facility",
    link: "https://unfccc.int/event/guidance-to-the-green-climate-fund-and-guidance-to-the-global-environment-facility",
    date: "07 Nov 2022",
    time: "16:00 - 17:30",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    title: "LEG@20: Twenty Years of adaptation Support to the LDCs’",
    link: "https://unfccc.int/event/leg20-twenty-years-of-adaptation-support-to-the-ldcs",
    date: "07 Nov 2022",
    time: "16:00 - 18:00",
    room: "Meeting Room 21",
    access: "Open meeting",
  },
  {
    title:
      "Overflow for plenary Nefertiti - First Part of the High-Level Segment",
    link: "https://unfccc.int/event/overflow-for-plenary-nefertiti-first-part-of-the-high-level-segment",
    date: "07 Nov 2022",
    time: "16:00 - 18:00",
    room: "Plenary - Ramses",
    access: "Open meeting",
  },
  {
    title:
      "Rules, modalities and procedures for the mechanism established by Article 6.4, of the Paris Agreement and referred to in decision 3/CMA.3",
    link: "https://unfccc.int/event/rules-modalities-and-procedures-for-the-mechanism-established-by-article-64-of-the-paris-agreement-0",
    date: "07 Nov 2022",
    time: "16:00 - 18:00",
    room: "Meeting Room 2",
    access: "Open meeting",
  },
  {
    title: "International Society for Ecological Economics (ISEE)",
    link: "https://unfccc.int/event/international-society-for-ecological-economics-isee-2",
    date: "07 Nov 2022",
    time: "16:30 - 17:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Abibimman Foundation",
    link: "https://unfccc.int/event/abibimman-foundation-19",
    date: "07 Nov 2022",
    time: "17:00 - 17:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "European Investment Bank: Financing a global just transition to climate neutrality",
    link: "https://unfccc.int/event/european-investment-bank-financing-a-global-just-transition-to-climate-neutrality",
    date: "07 Nov 2022",
    time: "17:00 - 17:30",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title:
      "Common metrics to calculate the carbon dioxide equivalence of greenhouse gases",
    link: "https://unfccc.int/event/common-metrics-to-calculate-the-carbon-dioxide-equivalence-of-greenhouse-gases",
    date: "07 Nov 2022",
    time: "17:00 - 18:00",
    room: "Meeting Room 5",
    access: "Open meeting",
  },
  {
    title:
      "INFORMAL CONSULTAION- SBI19 : Matters relating to capacity-building",
    link: "https://unfccc.int/event/informal-consultaion-sbi19-matters-relating-to-capacity-building",
    date: "07 Nov 2022",
    time: "17:00 - 18:00",
    room: "Meeting Room 4",
    access: "Open meeting",
  },
  {
    title:
      "Linkages between the Technology Mechanism and the Financial Mechanism of the Convention",
    link: "https://unfccc.int/event/linkages-between-the-technology-mechanism-and-the-financial-mechanism-of-the-convention-2",
    date: "07 Nov 2022",
    time: "17:00 - 18:00",
    room: "Meeting Room 3",
    access: "Open meeting",
  },
  {
    title: "Forests and Climate Leaders Partnership (FCLP) Summit",
    link: "https://unfccc.int/event/forests-and-climate-leaders-partnership-fclp-summit",
    date: "07 Nov 2022",
    time: "17:00 - 19:00",
    room: "Meeting Room 20",
    access: "Open meeting",
  },
  {
    title: "Marrakech Partnership Workshop",
    link: "https://unfccc.int/event/marrakech-partnership-workshop",
    date: "07 Nov 2022",
    time: "17:00 - 19:00",
    room: "Action Event Room 2 - Lotus",
    access: "Limited access",
  },
  {
    title:
      "Session 7: UGIH city-focused innovation and implementation sessions - focusing on Goyang city demonstration pilot and extension of methodology toward global cities",
    link: "https://unfccc.int/event/session-7-ugih-city-focused-innovation-and-implementation-sessions-focusing-on-goyang-city",
    date: "07 Nov 2022",
    time: "17:00 - 18:00",
    room: "Innovation-Hub Pavilion",
    access: "Open meeting",
  },
  {
    title:
      "1st meeting of the Contact Group: Administrative, financial and institutional matters",
    link: "https://unfccc.int/event/1st-meeting-of-the-contact-group-administrative-financial-and-institutional-matters",
    date: "07 Nov 2022",
    time: "17:30 - 19:00",
    room: "Meeting Room 17",
    access: "Open meeting",
  },
  {
    title:
      "STAND: Amazonia Against the Clock: Where and How to Protect 80% by 2025",
    link: "https://unfccc.int/event/stand-amazonia-against-the-clock-where-and-how-to-protect-80-by-2025",
    date: "07 Nov 2022",
    time: "17:30 - 18:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "SIDs Daily Coordination Evening Meeting",
    link: "https://unfccc.int/event/sids-daily-coordination-evening-meeting-7",
    date: "07 Nov 2022",
    time: "18:00 - 19:00",
    room: "Meeting Room 16",
    access: "Open meeting",
  },
  {
    title: "Italy",
    link: "https://unfccc.int/event/italy-1",
    date: "07 Nov 2022",
    time: "18:30 - 19:00",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title: "France",
    link: "https://unfccc.int/event/france",
    date: "07 Nov 2022",
    time: "20:15 - 20:45",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title: "Africa Carbon Markets",
    link: "https://unfccc.int/event/africa-carbon-markets",
    date: "08 Nov 2022",
    time: "08:00 - 09:30",
    room: "Action Event Room 1 - Ibis",
    access: "Open meeting",
  },
  {
    title: "Global Warming Mitigation Project",
    link: "https://unfccc.int/event/global-warming-mitigation-project-2",
    date: "08 Nov 2022",
    time: "09:00 - 09:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "Implementation of the Climate Roadmap by African Climate Commissions",
    link: "https://unfccc.int/event/implementation-of-the-climate-roadmap-by-african-climate-commissions",
    date: "08 Nov 2022",
    time: "09:00 - 11:00",
    room: "Meeting Room 25",
    access: "Open meeting",
  },
  {
    title:
      "University of California: UC Berkeley Student Delegation Share Climate Priorities",
    link: "https://unfccc.int/event/university-of-california-uc-berkeley-student-delegation-share-climate-priorities",
    date: "08 Nov 2022",
    time: "09:30 - 10:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "Accelerating the industrial - how to join forces in an open and inclusive Climate Club",
    link: "https://unfccc.int/event/accelerating-the-industrial-how-to-join-forces-in-an-open-and-inclusive-climate-club",
    date: "08 Nov 2022",
    time: "10:00 - 12:00",
    room: "Meeting Room 29",
    access: "Open meeting",
  },
  {
    title:
      "INFORMAL CONSULTATIONS - SBSTA 15: Guidance on cooperative approaches referred to in Article 6, paragraph 2, of the Paris Agreement and in decision 2/CMA.3",
    link: "https://unfccc.int/event/informal-consultations-sbsta-15-guidance-on-cooperative-approaches-referred-to-in-article-6",
    date: "08 Nov 2022",
    time: "10:00 - 12:00",
    room: "Meeting Room 2",
    access: "Open meeting",
  },
  {
    title:
      "CONTACT GROUP - SBSTA 9 / SBI 8 Joint CG on the First Global Stock take",
    link: "https://unfccc.int/event/contact-group-sbsta-9/sbi-8-joint-cg-on-the-first-global-stock-take",
    date: "08 Nov 2022",
    time: "10:00 - 11:00",
    room: "Meeting Room 17",
    access: "Open meeting",
  },
  {
    title: "Contact Group on CMA 8(e) New Collective Quantified Goal",
    link: "https://unfccc.int/event/contact-group-on-cma-8e-new-collective-quantified-goal",
    date: "08 Nov 2022",
    time: "10:00 - 11:00",
    room: "Meeting Room 1",
    access: "Open meeting",
  },
  {
    title:
      "Heads of State Summit for the launch of the Eastern Mediterranean and Middle East (EMME) Climate Change Initiative (EMME-CCI)",
    link: "https://unfccc.int/event/heads-of-state-summit-for-the-launch-of-the-eastern-mediterranean-and-middle-east-emme-climate",
    date: "08 Nov 2022",
    time: "10:00 - 11:00",
    room: "Meeting Room 23",
    access: "Open meeting",
  },
  {
    title:
      "Informal Consultation on SBI 17(c) First periodic assessment referred to in paragraph 69 of decision 1/CP 21",
    link: "https://unfccc.int/event/informal-consultation-on-sbi-17c-first-periodic-assessment-referred-to-in-paragraph-69-of-decision-1",
    date: "08 Nov 2022",
    time: "10:00 - 11:00",
    room: "Meeting Room 3",
    access: "Open meeting",
  },
  {
    title:
      "INFORMAL CONSULTATIONS - SBSTA7 /SBI 10: Koronivia Joint on Agriculture",
    link: "https://unfccc.int/event/informal-consultations-sbsta7/sbi-10-koronivia-joint-on-agriculture",
    date: "08 Nov 2022",
    time: "10:00 - 11:00",
    room: "Meeting Room 4",
    access: "Open meeting",
  },
  {
    title:
      "INFORMAL CONSULTATIONS- CMA 5 (a): Provision of financial and technical support to developing country Parties for reporting and capacity-building",
    link: "https://unfccc.int/event/informal-consultations-cma-5-a-provision-of-financial-and-technical-support-to-developing-country",
    date: "08 Nov 2022",
    time: "10:00 - 11:00",
    room: "Meeting Room 5",
    access: "Open meeting",
  },
  {
    title: 'Opening session "Transparency: Achievements and Outlook"',
    link: "https://unfccc.int/event/opening-session-transparency-achievements-and-outlook",
    date: "08 Nov 2022",
    time: "10:00 - 11:00",
    room: "Capacity-Building Hub",
    access: "Open meeting",
  },
  {
    title:
      "Session 1:  Transforming Cities – Money! The Role of Finance and Capital",
    link: "https://unfccc.int/event/session-1-transforming-cities-money-the-role-of-finance-and-capital",
    date: "08 Nov 2022",
    time: "10:00 - 11:00",
    room: "Innovation-Hub Pavilion",
    access: "Open meeting",
  },
  {
    title: "Delivery on Paris Agreement through data",
    link: "https://unfccc.int/event/delivery-on-paris-agreement-through-data",
    date: "08 Nov 2022",
    time: "10:00 - 11:30",
    room: "Action Event Room 1 - Ibis",
    access: "Open meeting",
  },
  {
    title:
      "ICCI: State of the Cryosphere 2022: Growing Climate Induced Changes in Polar and Mountain Regions Causing Increasing Losses Across the Globe",
    link: "https://unfccc.int/event/icci-state-of-the-cryosphere-2022-growing-climate-induced-changes-in-polar-and-mountain-regions",
    date: "08 Nov 2022",
    time: "10:00 - 10:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "OHCHR: UN Human Rights and Right Here, Right Now Global Climate Alliance Launch Human Rights-Based Climate Commitments and Upcoming Global Summit",
    link: "https://unfccc.int/event/ohchr-un-human-rights-and-right-here-right-now-global-climate-alliance-launch-human-rights-based",
    date: "08 Nov 2022",
    time: "10:00 - 10:30",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title: "Delivery of national statement",
    link: "https://unfccc.int/event/delivery-of-national-statement",
    date: "08 Nov 2022",
    time: "10:30 - 13:00",
    room: "Plenary - Nefertiti",
    access: "Open meeting",
  },
  {
    title: "Wilfrid Laurier University: Ghana Youth Film Program",
    link: "https://unfccc.int/event/wilfrid-laurier-university-ghana-youth-film-program",
    date: "08 Nov 2022",
    time: "10:30 - 11:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Accelerating Adaptation in Africa: COP 27 Leaders' Event",
    link: "https://unfccc.int/event/accelerating-adaptation-in-africa-cop-27-leaders-event",
    date: "08 Nov 2022",
    time: "11:00 - 12:30",
    room: "Meeting Room 20",
    access: "Open meeting",
  },
  {
    title:
      "INFORMAL CONSULTATIONS - SBSTA 10 (a): Research and Systematic Observation",
    link: "https://unfccc.int/event/informal-consultations-sbsta-10-a-research-and-systematic-observation",
    date: "08 Nov 2022",
    time: "11:00 - 12:00",
    room: "Meeting Room 3",
    access: "Open meeting",
  },
  {
    title:
      "INFORMAL CONSULTATIONS - SBSTA 6 / SBI 16: Santiago Network of the WIM",
    link: "https://unfccc.int/event/informal-consultations-sbsta-6/sbi-16-santiago-network-of-the-wim",
    date: "08 Nov 2022",
    time: "11:00 - 12:00",
    room: "Meeting Room 4",
    access: "Open meeting",
  },
  {
    title:
      "INFORMAL CONSULTATIONS- SBI 4 (c): Financial and Technical Support(FTS)",
    link: "https://unfccc.int/event/informal-consultations-sbi-4-c-financial-and-technical-supportfts",
    date: "08 Nov 2022",
    time: "11:00 - 12:00",
    room: "Meeting Room 5",
    access: "Open meeting",
  },
  {
    title: "Session 2:  Transforming Cities – Capabilities and Mindsets",
    link: "https://unfccc.int/event/session-2-transforming-cities-capabilities-and-mindsets",
    date: "08 Nov 2022",
    time: "11:00 - 12:00",
    room: "Innovation-Hub Pavilion",
    access: "Open meeting",
  },
  {
    title:
      "MANDATED EVENT - GST / TD Round Table 3 on Means of Implementation and Support",
    link: "https://unfccc.int/event/mandated-event-gst/td-round-table-3-on-means-of-implementation-and-support",
    date: "08 Nov 2022",
    time: "11:00 - 13:00",
    room: "Side Event Room 5 - Memphis",
    access: "Open meeting",
  },
  {
    title:
      "WMO: The Water Imperative for Climate Action (ahead of High-Level roundtable on Water and Security)",
    link: "https://unfccc.int/event/wmo-the-water-imperative-for-climate-action-ahead-of-high-level-roundtable-on-water-and-security",
    date: "08 Nov 2022",
    time: "11:00 - 11:30",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title: "CAN: Climate Action Network Press Briefing on COP27",
    link: "https://unfccc.int/event/can-climate-action-network-press-briefing-on-cop27-0",
    date: "08 Nov 2022",
    time: "11:30 - 12:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "ECOWAS: West Africa’s expectations for COP27 and ECOWAS Regional Climate Strategy",
    link: "https://unfccc.int/event/ecowas-west-africa-s-expectations-for-cop27-and-ecowas-regional-climate-strategy",
    date: "08 Nov 2022",
    time: "11:30 - 12:00",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title:
      "NGO constituencies and transparency: perspectives and opportunities for engagement",
    link: "https://unfccc.int/event/ngo-constituencies-and-transparency-perspectives-and-opportunities-for-engagement-0",
    date: "08 Nov 2022",
    time: "11:30 - 13:00",
    room: "Capacity-Building Hub",
    access: "Open meeting",
  },
  {
    title: "Buddhist Tzu Chi Foundation",
    link: "https://unfccc.int/event/buddhist-tzu-chi-foundation-18",
    date: "08 Nov 2022",
    time: "12:00 - 12:30",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title:
      "South Africa: President Cyril Ramaphosa to host a Press Conference during COP27",
    link: "https://unfccc.int/event/south-africa-president-cyril-ramaphosa-to-host-a-press-conference-during-cop27",
    date: "08 Nov 2022",
    time: "12:00 - 12:30",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title:
      "CONTACT - GROUP SBSTA 12 / SBI 20 Matters relating to the forum on the impact of the implementation of response measures serving the Convention, the Kyoto Protocol and the Paris Agreement",
    link: "https://unfccc.int/event/contact-group-sbsta-12/sbi-20-matters-relating-to-the-forum-on-the-impact-of-the-implementation-of",
    date: "08 Nov 2022",
    time: "12:00 - 13:00",
    room: "Meeting Room 3",
    access: "Open meeting",
  },
  {
    title: "INFORMAL CONSULTATIONS - SBSTA 5 / SBI 15: Report of the WIM ExCom",
    link: "https://unfccc.int/event/informal-consultations-sbsta-5/sbi-15-report-of-the-wim-excom",
    date: "08 Nov 2022",
    time: "12:00 - 13:00",
    room: "Meeting Room 4",
    access: "Open meeting",
  },
  {
    title:
      "INFORMAL CONSULTATIONS - SBSTA 8 / SBI 7 : Matters relating to the work programme for urgently scaling up mitigation ambition and implementation referred to in paragraph 27 of decision 1/CMA.3",
    link: "https://unfccc.int/event/informal-consultations-sbsta-8/sbi-7-matters-relating-to-the-work-programme-for-urgently-scaling-up",
    date: "08 Nov 2022",
    time: "12:00 - 13:00",
    room: "Meeting Room 17",
    access: "Open meeting",
  },
  {
    title:
      "INFORMAL CONSULTATIONS – SBI 5: Matters relating to the clean development mechanism registry referred to in paragraph 75(b) of the annex to decision 3/CMA.3",
    link: "https://unfccc.int/event/informal-consultations-sbi-5-matters-relating-to-the-clean-development-mechanism-registry-referred",
    date: "08 Nov 2022",
    time: "12:00 - 13:00",
    room: "Meeting Room 2",
    access: "Open meeting",
  },
  {
    title:
      "INFORMAL CONSULTATIONS- SBI 4 (b): First IC of the Report of the Consultative Group of Experts",
    link: "https://unfccc.int/event/informal-consultations-sbi-4-b-first-ic-of-the-report-of-the-consultative-group-of-experts",
    date: "08 Nov 2022",
    time: "12:00 - 13:00",
    room: "Meeting Room 5",
    access: "Open meeting",
  },
  {
    title: "OVERFLOW - INFORMAL CONSULTATIONS - SBSTA 5 / SBI 15",
    link: "https://unfccc.int/event/overflow-informal-consultations-sbsta-5/sbi-15",
    date: "08 Nov 2022",
    time: "12:00 - 13:00",
    room: "Meeting Room 6",
    access: "Open meeting",
  },
  {
    title:
      "Session 3: Supply- and demand-side barriers faced by women climate-tech entrepreneurs in Africa: practical tools to build capacities of ESOs, start-ups and investors",
    link: "https://unfccc.int/event/session-3-supply-and-demand-side-barriers-faced-by-women-climate-tech-entrepreneurs-in-africa",
    date: "08 Nov 2022",
    time: "12:00 - 13:00",
    room: "Innovation-Hub Pavilion",
    access: "Open meeting",
  },
  {
    title:
      "France, Senegal, the Netherlands and Global Center on Adaptation: COP 27 Leaders’ Event: Accelerating Adaptation in Africa",
    link: "https://unfccc.int/event/france-senegal-the-netherlands-and-global-center-on-adaptation-cop-27-leaders-event-accelerating",
    date: "08 Nov 2022",
    time: "12:30 - 13:00",
    room: "Press Conference Room - Cairo",
    access: "Open meeting",
  },
  {
    title: "Global Campaign to Demand Climate Justice",
    link: "https://unfccc.int/event/global-campaign-to-demand-climate-justice-0",
    date: "08 Nov 2022",
    time: "12:30 - 13:00",
    room: "Press Conference Room - Luxor",
    access: "Open meeting",
  },
  {
    title: "Continuation of national statements",
    link: "https://unfccc.int/event/continuation-of-national-statements",
    date: "08 Nov 2022",
    time: "13:00 - 18:00",
    room: "Plenary - Nefertiti",
    access: "Open meeting",
  },
  {
    title:
      "Informal meeting convened by the SBSTA chair on views submitted by parties on how to enhance climate action on land",
    link: "https://unfccc.int/event/informal-meeting-convened-by-the-sbsta-chair-on-views-submitted-by-parties-on-how-to-enhance-climate",
    date: "08 Nov 2022",
    time: "13:00 - 14:00",
    room: "Meeting Room 2",
    access: "Open meeting",
  },
  {
    title:
      "MANDATED EVENT: Assessing adaptation needs: findings from IPCC WGII contribution to AR6",
    link: "https://unfccc.int/event/mandated-event-assessing-adaptation-needs-findings-from-ipcc-wgii-contribution-to-ar6",
    date: "08 Nov 2022",
    time: "13:00 - 14:30",
    room: "Side Event Room 3 - Hatshepsut",
    access: "Open meeting",
  }
];

module.exports = meetings;
